### ISSUE TITLE
Issue with predicting words

### ISSUE THREAD

**Issue by momalekabid** [PinzhenChen/unifiedRevdicDefmod#1]
How do I get the top n words for a given prediction from the model? I trained and predicted using train_revdict.py, but when I try to load the sgns vector in my output file I can't use it with gensim imported word2vec or fasttext. Could you please explain that last part to me? Thanks for your time :)

**Comment by PinzhenChen** [comment]
Hi,

Perhaps the scoring file to look at is `code/utils/score.py` in which we scored MSE, cosine, and ranking. [This function](https://github.com/PinzhenChen/unifiedRevdicDefmod/blob/438d0e1f143542e1cdac8a7bb8e878e94835ad37/code/utils/score.py#L147) finds the (average) rank of the gold within predictions. [This](https://github.com/PinzhenChen/unifiedRevdicDefmod/blob/438d0e1f143542e1cdac8a7bb8e878e94835ad37/code/utils/score.py#L156) may also be of interest if you want to have accuracy@cutoff.

**Comment by momalekabid** [comment]
Thanks, that helped -- one more question; I tested with fasttext instead of word2vec and got a lot of ambigous word vector results (perhaps due to the character n-gram subword embeddings integrated into fasttext). Is this expected compared to word2vec?

**Comment by PinzhenChen** [comment]
Glad to hear that. Regarding your question, it depends on how you quantify "ambiguous"? I think the model architecture, embedding architecture, and also the nature of the data will affect the end performance. If you refer to this [paper](https://aclanthology.org/2022.aacl-short.2), reverse dictionary accuracies@1 for many models are just single digits; also we see MSE and cosine vary dramatically across different word embedding architectures in this [paper](https://aclanthology.org/2022.semeval-1.8/).
